# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0006_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='access_level',
            field=models.CharField(blank=True, choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], max_length=8, null=True, verbose_name='Access level'),
        ),
        migrations.AddField(
            model_name='column',
            name='metadata_access_level',
            field=models.CharField(blank=True, choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], max_length=8, null=True, verbose_name='Metadata access level'),
        ),
        migrations.AddField(
            model_name='database',
            name='access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Access level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='metadata_access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Metadata access level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Access level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='metadata_access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Metadata access level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Access level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='metadata_access_level',
            field=models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], default='PRIVATE', max_length=8, verbose_name='Metadata access level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='query_string',
            field=models.CharField(help_text='Prototype of this function in a SQL query.', max_length=256, verbose_name='Query string'),
        ),
    ]
