# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0011_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='metadata_access_level',
        ),
    ]
