# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0019_column_index_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='index_for',
            field=models.CharField(blank=True, default=b'', help_text='The columns which this column is an index for (e.g. for pgSphere).', max_length=256, verbose_name='Index for'),
        ),
    ]
