# Generated by Django 2.1.3 on 2018-11-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0023_python3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('table__schema__order', 'table__order', 'order'), 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ('order',), 'verbose_name': 'Function', 'verbose_name_plural': 'Functions'},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ('order',), 'verbose_name': 'Schema', 'verbose_name_plural': 'Schemas'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('schema__order', 'order'), 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
    ]
