# Generated by Django 5.2.10 on 2026-01-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0033_refactor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='index_for',
        ),
    ]
