# Generated by Django 5.2.13 on 2026-04-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_metadata', '0034_remove_column_index_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='published',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='table',
            name='published',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Published'),
        ),
    ]
