# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_auth', '0007_profile_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
