# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_query', '0011_queryjob_native_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryjob',
            name='query_language',
            field=models.CharField(max_length=16),
        ),
    ]
