# Generated by Django 5.2.12 on 2026-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_query', '0028_alter_queryarchivejob_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryjob',
            name='status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
