repos:
- repo: https://github.com/pycqa/isort
  rev: '5.10.1'
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.6.0'
  hooks:
  - id: autopep8
- repo: https://github.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
    - id: flake8
      exclude: ^.*/migrations/.*$
