language: python
cache: pip
dist: bionic

python:
- 3.6
- 3.7

addons:
  mariadb: '10.3'
  postgresql: '10'

env:
- DB=mysql
- DB=postgres

before_install:
- sudo apt-get -qq update

install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install mysqlclient
- pip install psycopg2-binary
- pip install coveralls

before_script:
- sh -c "cp testing/config/settings/$DB.py testing/config/settings/local.py; fi"
- mkdir testing/log testing/download
- mysql < testing/sql/mysql/test.sql
- psql -U postgres -f testing/sql/postgres/test.sql
- cat ../daiquiri/testing/sql/mysql/data/* | mysql
- cat ../daiquiri/testing/sql/postgres/data/* | psql -U postgres test_daiquiri_data

script:
- coverage run testing/runtests.py

after_success:
- coveralls
