# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('daiquiri_archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the collection.', max_length=32, verbose_name='Name')),
                ('access_level', models.CharField(choices=[(b'PRIVATE', 'Private - access must be granted by group'), (b'INTERNAL', 'Internal - logged in users can access'), (b'PUBLIC', 'Public - anonymous visitors can access')], max_length=8, verbose_name='Access level')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups which have access to this function.', to='auth.Group', verbose_name='Groups')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'permissions': (('view_collection', 'Can view Collection'),),
            },
        ),
    ]
