# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_archive', '0003_rename_file_ids_to_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejob',
            name='data',
            field=jsonfield.fields.JSONField(help_text='Input data for archive creation.', verbose_name='Data'),
        ),
    ]
