# Generated by Django 2.1.3 on 2018-11-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_archive', '0004_python3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivejob',
            options={'ordering': ('start_time',), 'verbose_name': 'ArchiveJob', 'verbose_name_plural': 'ArchiveJobs'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
