# Generated by Django 3.2.12 on 2022-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_archive', '0006_alter_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejob',
            name='data',
            field=models.JSONField(help_text='Input data for archive creation.', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='archivejob',
            name='files',
            field=models.JSONField(help_text='List of files in the archive.', verbose_name='Files'),
        ),
    ]
