# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField()),
                ('run_id', models.CharField(max_length=256)),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'QUEUED'), (3, 'EXECUTING'), (4, 'COMPLETED'), (5, 'ERROR'), (6, 'ABORTED'), (7, 'UNKNOWN'), (8, 'HELD'), (9, 'SUSPENDED'), (10, 'ARCHIVED')])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('execution_duration', models.DateTimeField()),
                ('destruction_time', models.PositiveIntegerField()),
                ('job_type', models.PositiveSmallIntegerField(choices=[(1, 'Query')])),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start_time',),
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'permissions': (('view_job', 'Can view Job'),),
            },
        ),
    ]
