# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0005_details_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[(b'ORGANIZER', 'organizer'), (b'INVITED', 'invited'), (b'REGISTERED', 'registered'), (b'ACCEPTED', 'accepted'), (b'REJECTED', 'rejected')], default='REGISTERED', help_text='Status of the participant.', max_length=16, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
