# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0006_participant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='accepted',
        ),
    ]
