# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0007_remove_participant_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(help_text='Slug for the URL of the meeting', max_length=32, verbose_name='Slug'),
        ),
    ]
