# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0009_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment',
            field=models.CharField(blank=True, choices=[(b'CASH', 'cash'), (b'WIRE', 'wire transfer')], help_text='Type of payment for the participant.', max_length=32, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_complete',
            field=models.BooleanField(default=False, help_text='Designates whether the payment is completed.', verbose_name='Payment complete'),
        ),
    ]
