# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment',
            field=models.CharField(blank=True, help_text='Type of payment for the participant.', max_length=32, verbose_name='Payment'),
        ),
    ]
