# Generated by Django 2.1.3 on 2018-11-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0012_python3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ('participant', 'title'), 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('title',), 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('meeting', 'last_name', 'first_name'), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
