# Generated by Django 3.2.12 on 2022-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_meetings', '0014_alter_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Choices are given by settings.MEETINGS_PARTICIPANT_DETAIL_KEYS', null=True, verbose_name='Details'),
        ),
    ]
