# Generated by Django 4.2.4 on 2023-08-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_contact', '0006_alter_contactmessage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('announcement', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'urgent')], default='info', max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Announcement message',
                'verbose_name_plural': 'Announcement messages',
                'ordering': ('-updated', 'title'),
            },
        ),
    ]
