# Generated by Django 5.2.13 on 2026-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_tap', '0002_alter_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='indexed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='principal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='std',
            field=models.IntegerField(default=0),
        ),
    ]
