# Generated by Django 5.2.14 on 2026-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_tap', '0003_alter_column_indexed_alter_column_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('from_table', models.CharField(max_length=256)),
                ('target_table', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('utype', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'keys',
            },
        ),
        migrations.CreateModel(
            name='KeyColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_id', models.CharField(max_length=256)),
                ('from_column', models.CharField(max_length=256)),
                ('target_column', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'key_columns',
            },
        ),
        migrations.AlterField(
            model_name='column',
            name='arraysize',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
