PHASE_PENDING = 'PENDING'
PHASE_QUEUED = 'QUEUED'
PHASE_EXECUTING = 'EXECUTING'
PHASE_COMPLETED = 'COMPLETED'
PHASE_ERROR = 'ERROR'
PHASE_ABORTED = 'ABORTED'
PHASE_UNKNOWN = 'UNKNOWN'
PHASE_HELD = 'HELD'
PHASE_SUSPENDED = 'SUSPENDED'
PHASE_ARCHIVED = 'ARCHIVED'

PHASE_RUN = 'RUN'
PHASE_ABORT = 'ABORT'

PHASE_ACTIVE = (
    PHASE_PENDING,
    PHASE_QUEUED,
    PHASE_EXECUTING
)
