# Generated by Django 5.2.10 on 2026-01-28 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('abstract', models.TextField(default='')),
                ('proprietary_until', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=16)),
                ('copi', models.ManyToManyField(blank=True, related_name='copi_proposals', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
