# Generated by Django 2.2.8 on 2020-01-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_oai', '0003_record_set_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='datestamp',
            field=models.DateTimeField(db_index=True, verbose_name='OAI datestamp'),
        ),
    ]
