# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_jobs', '0010_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
