# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_jobs', '0012_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='error_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
