# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_query', '0004_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryjob',
            name='query_language',
            field=models.CharField(choices=[[b'mysql', b'MySQL SQL'], [b'adql', b'ADQL']], max_length=8),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='queue',
            field=models.CharField(choices=[[b'default', b'Default']], max_length=16),
        ),
    ]
