import sys
from django.utils.translation import ugettext_lazy as _

TAP_METADATA = [
    {
        'order': sys.maxsize - 1,
        'name': 'TAP_SCHEMA',
        'query_strings': ['TAP_SCHEMA'],
        'description': _('The TAP schema'),
        'tables': [
            {
                'order': 1,
                'name': 'schemas',
                'query_strings': ['TAP_SCHEMA', 'schemas'],
                'columns': [
                    {
                        'order': 1,
                        'name': 'id',
                        'description': 'The (internal) id of the schema',
                        'query_strings': ['id'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 2,
                        'name': 'schema_name',
                        'description': 'The name of the schema',
                        'query_strings': ['schema_name'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 3,
                        'name': 'utype',
                        'description': 'The utype of the schema',
                        'query_strings': ['utype'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 4,
                        'name': 'description',
                        'description': 'The description of the schema',
                        'query_strings': ['description'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    }
                ]
            },
            {
                'order': 2,
                'name': 'tables',
                'query_strings': ['TAP_SCHEMA', 'tables'],
                'columns': [
                    {
                        'order': 1,
                        'name': 'id',
                        'description': 'The (internal) id of the table',
                        'query_strings': ['id'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 2,
                        'name': 'schema_name',
                        'description': 'The name of the schema of this table',
                        'query_strings': ['schema_name'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 3,
                        'name': 'table_name',
                        'description': 'The name of the table',
                        'query_strings': ['table_name'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 4,
                        'name': 'table_type',
                        'description': 'The type of the table (table or view)',
                        'query_strings': ['table_type'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 5,
                        'name': 'utype',
                        'description': 'The utype of the table',
                        'query_strings': ['utype'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 6,
                        'name': 'description',
                        'description': 'The description of the table',
                        'query_strings': ['description'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 7,
                        'name': 'table_index',
                        'description': 'The index (order) of the table',
                        'query_strings': ['table_index'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 8,
                        'name': 'schema_id',
                        'description': 'The foreign key to the schema of this table',
                        'query_strings': ['schema_id'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': True,
                        'std': True,
                        'principal': False
                    }
                ]
            },
            {
                'order': 3,
                'name': 'columns',
                'query_strings': ['TAP_SCHEMA', 'columns'],
                'columns': [
                    {
                        'order': 1,
                        'name': 'id',
                        'description': 'The (internal) id of the column',
                        'query_strings': ['id'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 2,
                        'name': 'table_name',
                        'description': 'The name of the table of this column',
                        'query_strings': ['table_name'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 3,
                        'name': 'column_name',
                        'description': 'The name of the column',
                        'query_strings': ['column_name'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 4,
                        'name': 'datatype',
                        'description': 'The datatype of this column',
                        'query_strings': ['datatype'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 5,
                        'name': 'arraysize',
                        'description': 'The arraysize of this column',
                        'query_strings': ['arraysize'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 6,
                        'name': 'size',
                        'description': 'The size of this column (legacy)',
                        'query_strings': ['size'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 7,
                        'name': 'description',
                        'description': 'The description of the column',
                        'query_strings': ['description'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 8,
                        'name': 'utype',
                        'description': 'The utype of the column',
                        'query_strings': ['utype'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 9,
                        'name': 'unit',
                        'description': 'The unit of the column',
                        'query_strings': ['unit'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 10,
                        'name': 'ucd',
                        'description': 'The ucd of the column',
                        'query_strings': ['ucd'],
                        'datatype': 'char',
                        'arraysize': 256,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 11,
                        'name': 'principal',
                        'description': 'Designates whether this is a principal column',
                        'query_strings': ['principal'],
                        'datatype': 'unsignedInt',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 12,
                        'name': 'indexed',
                        'description': 'Designates whether this column is indexed',
                        'query_strings': ['indexed'],
                        'datatype': 'unsignedInt',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 13,
                        'name': 'std',
                        'description': 'Designates whether this column follows a standard',
                        'query_strings': ['std'],
                        'datatype': 'unsignedInt',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 14,
                        'name': 'column_index',
                        'description': 'The index (order) of the column',
                        'query_strings': ['column_index'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': False,
                        'std': True,
                        'principal': False
                    },
                    {
                        'order': 15,
                        'name': 'table_id',
                        'description': 'The foreign key to the table of this column',
                        'query_strings': ['table_id'],
                        'datatype': 'integer',
                        'arraysize': None,
                        'utype': '',
                        'ucd': '',
                        'unit': '',
                        'indexed': True,
                        'std': True,
                        'principal': False
                    }
                ]
            }
        ]
    }
]
