# Generated by Django 3.2.12 on 2022-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daiquiri_auth', '0013_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
